---
version: "3.8"
services:
  movies:
    image: srikanthonline/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    images: srikanthonline/paytrain:latest
    ports:
      - 82:80
  deploy:
    replicas: 3
  dth:
    image: srikanthonline/payrecharge:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: srikanthonline/payrecharge:latest
    ports:
      - 83:80
    deploy: null
    replicas: 3
